services:
  my-db:
    image: mysql:8.0
    container_name: my-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: room_reservation
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword" ]
      interval: 30s
      timeout: 10s
      retries: 5

  room-reservation:
    image: room-reservation
    container_name: room-reservation
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      my-db:
        condition: service_healthy
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db_data:

