server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/room_reservation
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  messages:
    basename: i18n/messages
    encoding: UTF-8
